print("According to all known laws of aviation, there is no way a bee should be able to fly.")
print("Its wings are too small to get its fat little body off the ground.")
print("The bee, of course, flies anyway because bees don't care what humans think is impossible.")
print("Yellow, black. Yellow, black. Yellow, black. Yellow, black.")
print("Ooh, black and yellow!")
print("Let's shake it up a little.")
print("Barry! Breakfast is ready!")
print("Coming!")
print("Hang on a second.")
print("Hello?")
print("Barry?")
print("Adam?")
print("Can you believe this is happening?")
print("I can't.")
print("I'll pick you up.")
print("Looking sharp.")
print("Use the stairs, Your father paid good money for those.")
print("Sorry. I'm excited.")
print("Here's the graduate.")
print("We're very proud of you, son.")