a = input("Wierd noun: ")
b = input("Verb ending in -ing: ")
c = input("Silly adjective: ")
d = input("The name of a food: ")
e = input("Quantity: ")
f = input("Famous person: ") 
g = input("Funky noise: ")
print(" ")
print("One day, bobby woke up and went to school with his favorite " + a+".")
print("He excitedly entered the classroom while "+ b + " with his friends.") 
print("Bobby was a very " + c + " kind of guy")
print("After class, he hurried to the cafeteria, excited to eat " + d + " for lunch, like he did ever single day" )
print("After his nutritious lunch of " + e + " calories, bobby went out to recess to play with " + f)
print("unfortunately, " + f + " slapped Bobby in the face, which caused him to yell out " + g +"!")